name: jalalidatepicker
description: Calendar , Datepicker and Date Convertor For Persian Date(Jalali or Shamsi date) with holiday
version: 1.0.4
homepage: https://github.com/mrmostafaei/jalalidatepicker

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  jiffy: ^4.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
